### ISSUE TITLE
v0.2.0 Roadmap

### ISSUE THREAD

**Issue by ydcjeff** [pytorch-ignite/code-generator#103]
We now have 2 versions of the app:
- v0.2.0 on https://code-generator.netlify.app/ (next version preview) from `main` branch
- v0.1.0 on https://share.streamlit.io/pytorch-ignite/code-generator from `master` branch

The new version is made with **Vue 3** while the old one is made with **Streamlit**.

### Features lacked in new app, present in old app

- [x] Introductory page - PR: #124 
- [x] Multiple templates - PR: #118 #119 #129 #131
- [x] TerminateOnNaN, TimeLimit, EarlyStopping, and Timer handlers - PR: #116 
- [x] Unit Testing Options - PR: #133 
- [x] Code copy button - PR: #106
- README markdown is not rendered

### Features lacked in old app, present in new app

- Resizable panes
- Deterministic Training
- Brand colors and styles
- Line numbers, file extensions appearance
- Customization (ofc with maintenance)
- Blob storage download link (shorter than base64 link)

### New features to be added in new version

- [x] Download successful message - PR: #109 
- [x] Make app looks good on mobile - Issue: #104, PR: #105 #108
- [x] Add respective file icons beside file names - PR: #110  

### Small fixes:

UI
- [x] scrolling bug (#151)
- [x] split between windows (#148)
- [x] disable trainer-logger tags if no template (#153 )

Set default configuration (#154 )
- [x] preconfigured handlers
- [x] checkpoints
- [x] out folder
- [x] tb by default

Misc
- [x] ClearML (#149)
- [x] Export to Colab (#162 )
- [x] Link v0.2.0 URL in old code-generator app (#159 )
- [x] Bug with closing help window (#156 )
- [x] New line trimming: like Jinja does maybe? (#152 )
- [x] pytest in requirements (#150)
- [x] READMEs update (#155)
- [x] larger epochs, batch size (#155)

cc @vfdev-5 @trsvchn

**Comment by vfdev-5** [comment]
@ydcjeff pleaes remove `download_datasets(config.data_path)` from segmentation template. Let's raise an issue if no dataset is found. We can also suggest how to download it.

**Comment by vfdev-5** [comment]
@ydcjeff there is still present uncoverd issue we already talked about : 
- select template
- click download => ... Please input in Loggers tab.
